server:
  port: 8080

spring:
  application:
    name: student-portal
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/student_portal}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  session:
    jdbc:
      flush-mode: on_save
      table-name: SPRING_SESSION
      initialize-schema: always
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  jackson:
    serialization:
      write-dates-as-timestamps: false